### Site info:
title: TRY IT
tagline: Life is the times you breath, and the moment you hold it
author: Lin Jiang
email: lj-blog@outlook.com
description: "this is my blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "blog"
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://www.haplont.com/blog" # the base hostname & protocol for your site
locale: zh_CN

### Personal info and site tools info:
github_username:  botma
disqus_shortname: wwwhaplontcom
favicon:     "/blog/images/Linux.png"
aboutme: Hi, I'm Lin Jiang, welcome to visit my blog.  # these are shown on aboutme-sidebar.
aboutme_photo: /blog/images/Linux.png # your photo.
google_analytics_key: UA-72316951-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "cn" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
    cn:
      Aboutme: ""
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Recent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
      Google_search: "站内搜索"
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Lin Jiang
        href: http://www.haplont.com/blog
        title: Another Jekyll blog theme


### Build settings
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]
paginate: 10
excerpt_separator: <!-- more -->
permalink: /:year/:month/:day/:title
exclude: ['tmp']
